[package]
name = "dds-bridge-sys"
version = "0.1.0"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2021"
description = "Generated bindings to DDS, the double dummy solver for bridge"
repository = "https://github.com/jdh8/dds-bridge-sys"
license = "Apache-2.0"
categories = ["game-development", "external-ffi-bindings", "no-std"]
keywords = ["bridge", "double-dummy"]
exclude = ["/vendor/hands", "/vendor/doc"]

[build-dependencies]
anyhow = "1.0.86"
bindgen = "0.69.4"
